# Generated by Django 3.2 on 2021-05-18 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_author_profie_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='profie_picture',
            new_name='profile_picture',
        ),
    ]
